### ISSUE TITLE
WIFI Signal Strength

### ISSUE THREAD

**Issue by MuruganDurai** [devstepbcn/react-native-android-wifi#1]
Hi, How Can I get WIFI Signal Strength using this module? Any code sample would be appreciable.

**Comment by devstepbcn** [comment]
Hi @MuruganDurai,

In the new module version 0.0.3, you can retrieve the wifi signal strength. 

You can get the signal strength of the wifi that you are connected on, or scan all the wifi networks in range and get the signal strength of each.

You can find code samples in the updated readme file of the module.
