### ISSUE TITLE
It doesn't work with RN 0.43.0

### ISSUE THREAD

**Issue by thiensubs** [devstepbcn/react-native-android-wifi#10]
Maybe you should update this library, because when i add with npm and using in app. It doesn't work with RN 0.43.0 and react: ^16.0.0-alpha.6

**Comment by jamesjara** [comment]
which is the error? could you paste the output thanks

**Comment by diogoperillo** [comment]
It works for me with RN 0.44.0 and react 16.0.0-alpha.6
