### ISSUE TITLE
Suggest to add getServiceAddress() method

### ISSUE THREAD

**Issue by ytfhwfnh** [devstepbcn/react-native-android-wifi#11]
`	@ReactMethod`
`	public void getServerAddress(final Callback callback) {`
`		DhcpInfo dhcpinfo = wifi.getDhcpInfo();`
`		String stringip=longToIP(dhcpinfo.serverAddress);`
`		callback.invoke(stringip);`
`	}`

**Comment by devstepbcn** [comment]
hi @ytfhwfnh getDhcpServerAddress() method is now available, thank you!
