### ISSUE TITLE
loadWifiList() is returning a null wifiStringList even there are available connections !

### ISSUE THREAD

**Issue by DinukaManohara** [devstepbcn/react-native-android-wifi#12]
RN 0.44.0 CLI 2.0.1 
Android 7.0 EMUI 5.0 (Huawei GR5 2017)
All the other methods are working perfectly but this loadWifiList() is returning a null list ???

**Comment by dan-me** [comment]
@DinukaManohara  Some android systems need to open up a list of the wifi available on the phone's GPS

**Comment by jdeibe** [comment]
@dan-me I'm having the the same issue. No list of wi-fi from method loadWifiList(). What should be added to make it work?

**Comment by dan-me** [comment]
@jdeibe  What is the version of Android?  Do you have to open the phone GPS?

**Comment by jdeibe** [comment]
Android 7.0, Honor. I just noticed once I turn on GPS/Position from settings in my app it works.

**Comment by dan-me** [comment]
<https://issuetracker.google.com/issues/37060483>

**Comment by ParthBarot-BoTreeConsulting** [comment]
Thanks @dan-me , we are already using this permission but this would help someone who is using this module.

@jdeibe We are using the following, and its working fine.

``` xml
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

**Comment by SirNeuman** [comment]
I had this same problem even after adding the permissions. Then I went into my app settings on my device and went into permissions. I realized that the "location" permission for my app was toggled to off. I toggled it on and now i do get the list.

**Comment by tolik85** [comment]
@SirNeuman Thanks! This was exactly my problem!

**Comment by tripflex** [comment]
Yup I can confirm this is specifically related to the `ACCESS_FINE_LOCATION`, which I only figured out through numerous trial and errors on a cordova plugin I forked for managing WiFi:
https://github.com/tripflex/WifiWizard2/pull/8

**Comment by tolik85** [comment]
My app keeps crashing saying there's no ACCESS_FINE_LOCATION in the AndroidManifest, although it is there. Also, as @SirNeuman said, the location permission for my app in Android settings was toggled off and the app was not asking for user's permission with PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION);, but crashes instead (until I manually turn the location toggle on). Why is that?

**Comment by stephane-r** [comment]
Hi guys ! Anyone have solution about this problem ? I'm on Huawai, API 27

**Comment by ParthBarot-BoTreeConsulting** [comment]
I assume you have tried all the above permissions. 

One thing you can check is, which version you are on and does it work for older Android versions? Like, we have tested this on Android 7, not sure in new versions!

Thanks

**Comment by stephane-r** [comment]
Hi @ParthBarot-BoTreeConsulting 

Yes, you can see my AndroidManifest : 

```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus"/>

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
```

I try on Huawai P20 with Android 8.
