### ISSUE TITLE
Rescan Wifi List

### ISSUE THREAD

**Issue by santosh-btc** [devstepbcn/react-native-android-wifi#13]
I am trying to rescan wifi network list.

I did the following.

```
_onRefresh() {
     this.setState({refreshing: true});
     this.getWifiNetworks();
   }
```

```
getWifiNetworks() {
    wifi.loadWifiList((wifiStringList) => {
      var wifiArray = JSON.parse(wifiStringList);
      this.setState({
        wifiList: wifiArray,
      });
      let selectedSsidDefault = this.state.wifiList[this.state.selected1];
      this.setState({ ssid: selectedSsidDefault.SSID });
      this.setState({refreshing: false});

    },
      (error) => {
        console.log(error);
      }
    );
  }
```

```
refreshControl={
            <RefreshControl
              refreshing={this.state.refreshing}
              onRefresh={this._onRefresh.bind(this)}
            />
          }
```

but no luck. 

how can i rescan available wifi list?

**Comment by ParthBarot-BoTreeConsulting** [comment]
@santosh-btc Rescan is not implemented as it requires to register a `BroadcastReceiver`, which will behave asynchronously and triggers back the `onReceive` when scanning is finished. I am working on this item but facing some issues!

**Comment by ParthBarot-BoTreeConsulting** [comment]
@devstepbcn Any thoughts on this, I want to have the ability to forcefully rescan the wifi list but it requires to register `BroadcastReceiver` if we want to handle it async which may lead to another question that when hall we unregister it?

Instead, I am thinking of just starting the scan, then showing the loader for a few seconds and then fetch the list and show it again - Like, AJAX polling - which could partially solve this.

**Comment by ParthBarot-BoTreeConsulting** [comment]
@devstepbcn This has been merged already, Please close.

**Comment by devstepbcn** [comment]
Thanks @ParthBarot-BoTreeConsulting
