### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by asCii88** [devstepbcn/react-native-android-wifi#15]
Note: /react-native-android-wifi/android/src/main/java/com/devstepbcn/wifi/AndroidWifiModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Not sure what it is

**Comment by jlucier** [comment]
Got the same error on react-native: 0.46.4

Would love to find a solution.

**Comment by AlexanderKosianchuk** [comment]
.../node_modules/react-native-android-wifi/android/src/main/java/com/devstepbcn/wifi/AndroidWifiPackage.java:12: error: AndroidWifiPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class AndroidWifiPackage implements ReactPackage {
       ^
Note: .../node_modules/react-native-android-wifi/android/src/main/java/com/devstepbcn/wifi/AndroidWifiModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-android-wifi:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

Tried on RN 0.43 - 0.47 no success

**Comment by AlexanderKosianchuk** [comment]
Thanks, ok now on RN 0.42.3

**Comment by devstepbcn** [comment]
Thanks @AlexanderKosianchuk !
