### ISSUE TITLE
Remove/Forget the connected Wifi network from the device

### ISSUE THREAD

**Issue by ParthBarot-BoTreeConsulting** [devstepbcn/react-native-android-wifi#16]
@devstepbcn 

I wanted to disconnect and forget/remove the currently connected Wifi device. I have looked into the source for this feature, but then forked and implemented it. Would submit a PR!

**Comment by devstepbcn** [comment]
Thanks @ParthBarot-BoTreeConsulting!

**Comment by ParthBarot-BoTreeConsulting** [comment]
@devstepbcn Welcome! I have verified this on multiple Android devices and it works fine. Though, please close it once you get a chance to verify this!

Thanks,
Parth
