### ISSUE TITLE
wifi.findAndConnect how do i listen to the response?

### ISSUE THREAD

**Issue by wowzaaa** [devstepbcn/react-native-android-wifi#2]
Hey

so if i try to connect to a wifi network using wifi.findAndConnect ... the responso only tells me if it is in range not if i got connected ... how do i know if the connection succeeded?

**Comment by devstepbcn** [comment]
Hey wowzaaa

Android doesn’t provide a callback when you try to connect to a wifi. You have to listen for connectivity changes to know if connection succeeded. You can use [NetInfo](https://facebook.github.io/react-native/docs/netinfo.html) from React Native Components.
