### ISSUE TITLE
findAndConnect clones WiFi configuration on Android 6

### ISSUE THREAD

**Issue by GRouslan** [devstepbcn/react-native-android-wifi#20]
If it is an already configured by user connection on Android 6 findAndConnect method clones WiFi configuration and connects to the cloned one.

According to  [ Android 6.0 Changes](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-network)

> Your apps can now change the state of WifiConfiguration objects only if you created these objects. You are not permitted to modify or delete WifiConfiguration objects created by the user or by other apps.

**Comment by ParthBarot-BoTreeConsulting** [comment]
@GRouslan See the changes I have added, it has forced wifi scanning and remove/forget wifi network when you don't need it. Maybe that can help you.

Thanks
