### ISSUE TITLE
getCurrentActivity() is not public in ReactContext; cannot be accessed from outside package

### ISSUE THREAD

**Issue by mtimofiiv** [devstepbcn/react-native-android-wifi#27]
Hello!

I am getting the following error when I try to build the Android version:

<img width="1195" alt="screen shot 2017-09-17 at 13 14 46" src="https://user-images.githubusercontent.com/428948/30520252-46bd8ed4-9baa-11e7-9644-066c9b58c7cc.png">

My React-Native version `0.47.2`, and installed the latest version of this module from the npm registry.

**Comment by mtimofiiv** [comment]
@dabush-eliel a clean re-install of the module seemed to help in our case!

**Comment by devstepbcn** [comment]
Class ReactContextBaseJavaModule already have method getCurrentActivity(), v0.0.38 fix this issue.
