### ISSUE TITLE
react-native-android-wifi install and Link doesnt work

### ISSUE THREAD

**Issue by Chatharaju** [devstepbcn/react-native-android-wifi#39]
Hi there, 

Followed the steps to install the library and tried linking both automatic and manually. When am trying to call the one of the method am getting an error "Undefined is not an object (evaluating "wifi.setEnabled"). Infact, same issue with other methods as well. 

Please let me know if I missed any steps to use this library. Thank you.

Cheers,
Vinay.

**Comment by devstepbcn** [comment]
Change the import to  
```javascript
import wifi from 'react-native-android-wifi';
```
Take a look to the Readme file and the Example app

**Comment by Zerquix18** [comment]
@devstepbcn I tried that and it still doesn't work. I'm using expo, and `react-native link` shows this:

```rnpm-install info Platform 'android' module react-native-android-wifi is already linked 
rnpm-install info Linking assets to ios project 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'pbxprojPath' of null```

**Comment by Chatharaju** [comment]
You mean I need to push the app into the device via Android SDK? I am using "react-native run-android" command to push the app

**Comment by Chatharaju** [comment]
I am using a real device.

**Comment by Zerquix18** [comment]
I'm using a real device too. I installed all dependencies, ran `react-native link`, `react-native run-android` (it should show at least 3 projects) and then `react-native start`

**Comment by Chatharaju** [comment]
Think I did the same:
1) npm install react-native-android-wifi --save
2) react-native link (Done Manual as well)
3) import wifi from 'react-native-android-wifi'; then
`ComponentDidMount() {
wifi.getSSID((ssid) => {
  console.log(ssid);
});
}`

This is exactly I have done. Is there anything else I need to do.

**Comment by Chatharaju** [comment]
Very wired but finally made it working. I have to restart the server, uninstall the app and install again. May be it is issue with WebStrom.
