### ISSUE TITLE
react-native-android-wifi has a changelog

### ISSUE THREAD

**Issue by natterstefan** [devstepbcn/react-native-android-wifi#42]
Hi @devstepbcn,

first of all, thanks for the module. I appreciate your work and effort. One question though, can you add a changelog or release tags or anything that can help to see the progress, breaking changes and other notes about new versions? That would be very helpful when one decides to upgrade your module or not.

Thank you.

**Comment by devstepbcn** [comment]
Thanks @natterstefan I started to tag the versions, if someday we have breaking changes I will start a changelog file.

**Comment by natterstefan** [comment]
@devstepbcn sounds good, thank you!
