### ISSUE TITLE
Wifi not connecting on Android Oreo API 26

### ISSUE THREAD

**Issue by cyphereza** [devstepbcn/react-native-android-wifi#43]
Anyone having the same issue? It is working on Lollipop and Nougat. But on Oreo, it seems that I couldn't connect to any wifi. It seems like it tries to connect for a while and then disconnect and connect to another saved wifi. When I manually try to connect to the wifi from wifi settings page, it wouldn't connect (manually) unless I forget the network.

**Comment by cyphereza** [comment]
It seems to be a problem with the code below. I saw a PR on that. Hopefully it gets approved and rectifies my issue.

`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
			conf.SSID = ssid;
		} else {
			conf.SSID = "\"" + ssid + "\"";
		}`

**Comment by gigby** [comment]
@cyphereza Thank you so much for your comment!))))
