### ISSUE TITLE
loadWifiList() is not working in android sdk 25 and above

### ISSUE THREAD

**Issue by appaaaa** [devstepbcn/react-native-android-wifi#49]
loadWifiList() is working in android sdk 23, 

but not working in sdk 25 and above..

How can I get wifilist? 

Anyone solve this?

**Comment by appaaaa** [comment]
I found that scanning is deprecated in api level P. but I should use scanning in my app. so I'm finding any alternative solution. anyone find it, notice me. 
if I find solution, I'll write here

**Comment by appaaaa** [comment]
I solve this. Above api level 26, needs  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

**Comment by devstepbcn** [comment]
Access-coarse-location permission added on manifest. Readme updated. App Examples updated.
