### ISSUE TITLE
Not connecting with open WIFI

### ISSUE THREAD

**Issue by sanmugamk** [devstepbcn/react-native-android-wifi#59]
I am new to react native & android. I am checking your example. When i connect to the secured wifi it is connecting and returning found true, that is cool. But when i connect to open network it not no established the connection, but it returning found true I am using Android 7.1.1.

If it is not a bug can anyone guide me to fix this?

**Comment by freerk** [comment]
I've created a fix and PR.

**Comment by devstepbcn** [comment]
Thanks @freerk for your PR!

**Comment by sanmugamk** [comment]
Thank you Guys :clap:
