### ISSUE TITLE
Connect to hidden WiFi networks

### ISSUE THREAD

**Issue by hassanmojab** [devstepbcn/react-native-android-wifi#63]
findAndConnect method can't connect to hidden WiFi networks.
Is it possible to add this feature or is there any other workarounds?

**Comment by hassanmojab** [comment]
I've added a new method connectToHiddenNetwork and created a PR.

**Comment by devstepbcn** [comment]
Hi @hassanmojab your PR has been merged, thank you for your collaboration!
