### ISSUE TITLE
forceWifiUsage permissions bug

### ISSUE THREAD

**Issue by bondparkerbond** [devstepbcn/react-native-android-wifi#73]
We are currently requesting an advanced permission ACTION_MANAGE_WRITE_SETTINGS when calling forceWifiUsage(true) on all Android SDK versions >= 23(M). However, this permission is only needed in SDK 23(specifically 6.0.0), as this was a bug and was fixed in all later versions including 6.0.1 and SDK 24+. We should not be prompting to extra permissions or checking canWrite permissions for SDK 24+ when calling forceWifiUsage.
More info:
https://stackoverflow.com/questions/32185628/connectivitymanager-requestnetwork-in-android-6-0#answer-33509180

**Comment by devstepbcn** [comment]
Thank you @bondparkerbond !
